//Course
export const REQUEST_API_ALL_COURSE_MODULES = 'REQUEST_API_ALL_COURSE_MODULES';
export const RECEIVE_API_ALL_COURSE_MODULES = 'RECEIVE_API_ALL_COURSE_MODULES';

//ExerciseAndResource
export const REQUEST_API_EXERCISE_RESOUCE_BY_ID = 'REQUEST_API_EXERCISE_RESOUCE_BY_ID';
export const RECEIVE_API_EXERCISE_RESOUCE_BY_ID = 'RECEIVE_API_EXERCISE_RESOUCE_BY_ID';
export const REQUEST_EXERCISE_RESULT = 'REQUEST_EXERCISEL_RESULT';
export const RECEIVE_EXERCISE_RESULT = 'RECEIVE_EXERCISE_RESULT';
export const REQUEST_API_RESOUCE_BY_ID = 'REQUEST_API_RESOUCE_BY_ID';
export const RECEIVE_API_RESOUCE_BY_ID = 'RECEIVE_API_RESOUCE_BY_ID';
export const PUT_API_EXERCISE_GOAL_RESULT = 'PUT_API_EXERCISE_GOAL_RESULT';
export const PUT_API_EXERCISE_RESOUCE = 'PUT_API_EXERCISE_RESOUCE';
export const PUT_API_EXERCISE_VIDEO_RESULT = 'PUT_API_EXERCISE_VIDEO_RESULT';
export const PUT_API_RESOUCE = 'PUT_API_RESOUCE';
export const RECEIVE_API_UPDATED_RESOUCE_ID = 'RECEIVE_API_UPDATED_RESOUCE_ID';

//Module

export const REQUEST_API_MODULE = 'REQUEST_API_MODULE';
export const RECEIVE_API_MODULE = 'RECEIVE_API_MODULE';
export const REQUEST_ALL_MODULE_EXERCISES = 'REQUEST_ALL_MODULE_EXERCISES';
export const RECEIVE_ALL_MODULE_EXERCISES = 'RECEIVE_ALL_MODULE_EXERCISES';
export const REQUEST_GET_MODULE_RESULT = 'REQUEST_GET_MODULE_RESULT';
export const RECEIVE_GET_MODULE_RESULT = 'RECEIVE_GET_MODULE_RESULT';
export const PUT_API_MODULE_DESCRIPTION = 'PUT_API_MODULE_DESCRIPTION';
export const PUT_API_MODULE_PROMISE_RESULT = 'PUT_API_MODULE_PROMISE_RESULT';

//OtherActions

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REQUEST_POST_DIALOG_MESSAGE = 'REQUEST_POST_DIALOG_MESSAGE';
export const RECEIVE_POST_DIALOG_MESSAGE = 'RECEIVE_POST_DIALOG_MESSAGE';
export const PUT_API_KP_EXPLORER_RESULT = 'PUT_API_KP_EXPLORER_RESULT';
export const PUT_API_QUESTION_ANSWER_RESULT = 'PUT_API_QUESTION_ANSWER_RESULT';
export const PUT_API_SORT_AND_EVAL_RESULT = 'PUT_API_SORT_AND_EVAL_RESULT';
export const REQUEST_SEND_SMS = 'REQUEST_SEND_SMS';
export const RECEIVE_SEND_SMS = 'RECEIVE_SEND_SMS';
export const REQUEST_SHARE_VIDEO = 'REQUEST_SHARE_VIDEO';
export const RECEIVE_SHARE_VIDEO = 'RECEIVE_SHARE_VIDEO';

//User

export const REQUEST_GET_CURRENT_USER = 'REQUEST_GET_CURRENT_USER';
export const RECEIVE_GET_CURRENT_USER = 'RECEIVE_GET_CURRENT_USER';
export const REQUEST_USER_DIALOGS = 'REQUEST_USER_DIALOGS';
export const RECEIVE_USER_DIALOGS = 'RECEIVE_USER_DIALOGS';
export const REQUEST_GET_USER_RESULT = 'REQUEST_GET_USER_RESULT';
export const RECEIVE_GET_USER_RESULT = 'RECEIVE_GET_USER_RESULT';
   


////Course
//REQUEST_API_ALL_COURSE_MODULES: 'REQUEST_API_ALL_COURSE_MODULES',
//    RECEIVE_API_ALL_COURSE_MODULES: 'RECEIVE_API_ALL_COURSE_MODULES',

//    //ExerciseAndResource
//REQUEST_API_EXERCISE_RESOUCE_BY_ID: 'REQUEST_API_EXERCISE_RESOUCE_BY_ID',
//RECEIVE_API_EXERCISE_RESOUCE_BY_ID: 'RECEIVE_API_EXERCISE_RESOUCE_BY_ID',

//REQUEST_EXERCISE_RESULT: 'REQUEST_EXERCISEL_RESULT',
//RECEIVE_EXERCISE_RESULT: 'RECEIVE_EXERCISE_RESULT',

//REQUEST_API_RESOUCE_BY_ID: 'REQUEST_API_RESOUCE_BY_ID',
//RECEIVE_API_RESOUCE_BY_ID: 'RECEIVE_API_RESOUCE_BY_ID',

//PUT_API_EXERCISE_GOAL_RESULT: 'PUT_API_EXERCISE_GOAL_RESULT',
//PUT_API_EXERCISE_RESOUCE: 'PUT_API_EXERCISE_RESOUCE',
//PUT_API_EXERCISE_VIDEO_RESULT: 'PUT_API_EXERCISE_VIDEO_RESULT',

//PUT_API_RESOUCE: 'PUT_API_RESOUCE',
//RECEIVE_API_UPDATED_RESOUCE_ID: 'RECEIVE_API_UPDATED_RESOUCE_ID',

////Module

//REQUEST_API_MODULE: 'REQUEST_API_MODULE',
//RECEIVE_API_MODULE: 'RECEIVE_API_MODULE',

//REQUEST_ALL_MODULE_EXERCISES: 'REQUEST_ALL_MODULE_EXERCISES',
//RECEIVE_ALL_MODULE_EXERCISES: 'RECEIVE_ALL_MODULE_EXERCISES',

//REQUEST_GET_MODULE_RESULT: 'REQUEST_GET_MODULE_RESULT',
//RECEIVE_GET_MODULE_RESULT: 'RECEIVE_GET_MODULE_RESULT',

//PUT_API_MODULE_DESCRIPTION: 'PUT_API_MODULE_DESCRIPTION',
//PUT_API_MODULE_PROMISE_RESULT: 'PUT_API_MODULE_PROMISE_RESULT',

////OtherActions

//LOGIN_REQUEST: 'LOGIN_REQUEST',
//LOGIN_SUCCESS: 'LOGIN_SUCCESS',
//LOGIN_FAILURE: 'LOGIN_FAILURE',

//REQUEST_POST_DIALOG_MESSAGE: 'REQUEST_POST_DIALOG_MESSAGE',
//RECEIVE_POST_DIALOG_MESSAGE: 'RECEIVE_POST_DIALOG_MESSAGE',

//PUT_API_KP_EXPLORER_RESULT: 'PUT_API_KP_EXPLORER_RESULT',
//PUT_API_QUESTION_ANSWER_RESULT: 'PUT_API_QUESTION_ANSWER_RESULT',

//PUT_API_SORT_AND_EVAL_RESULT: 'PUT_API_SORT_AND_EVAL_RESULT',
//PUT_API_SORT_AND_EVAL_RESULT: 'PUT_API_SORT_AND_EVAL_RESULT',

//REQUEST_SEND_SMS: 'REQUEST_SEND_SMS',
//RECEIVE_SEND_SMS: 'RECEIVE_SEND_SMS',

//REQUEST_SHARE_VIDEO: 'REQUEST_SHARE_VIDEO',
//RECEIVE_SHARE_VIDEO: 'RECEIVE_SHARE_VIDEO',

////User

//REQUEST_GET_CURRENT_USER: 'REQUEST_GET_CURRENT_USER',
//RECEIVE_GET_CURRENT_USER: 'RECEIVE_GET_CURRENT_USER',
//REQUEST_USER_DIALOGS: 'REQUEST_USER_DIALOGS',
//RECEIVE_USER_DIALOGS: 'RECEIVE_USER_DIALOGS',
//REQUEST_GET_USER_RESULT: 'REQUEST_GET_USER_RESULT',
//RECEIVE_GET_USER_RESULT: 'RECEIVE_GET_USER_RESULT'